# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tharghaz <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/11 17:51:18 by tharghaz          #+#    #+#              #
#    Updated: 2019/02/11 19:02:38 by tharghaz         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT=do_op
SRCS=srcs/ft_add.c \
	srcs/ft_atoi.c \
	srcs/ft_div.c \
	srcs/ft_min.c \
	srcs/ft_mod.c \
	srcs/ft_mult.c \
	srcs/main.c

all:
	gcc -o $(RESULT) $(SRCS)

clean:
	rm -f $(RESULT)

re: clean all
